{% set name = "whiteboxgui" %}
{% set version = "0.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 3b2e3bf315b70f49304cfe4ed9273901b809d53b69a150017803a8037ee24c60

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ipyfilechooser
    - ipytree
    - ipywidgets
    - python >=3.6
    - whitebox
    - xorg-libx11

test:
  imports:
    - whiteboxgui

about:
  home: https://github.com/giswqs/whiteboxgui
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "An interactive GUI for WhiteboxTools in a Jupyter-based environment"
  doc_url: https://giswqs.github.io/whiteboxgui
  dev_url: https://github.com/giswqs/whiteboxgui

extra:
  recipe-maintainers:
    - giswqs
