{% set name = "whiteboxgui" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c59dfccb244bc2d7b9ff77c63a81b77d0e1b4a6fc19476449e450e0da009a754

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - ipyfilechooser
    - ipytree
    - ipywidgets
    - python >={{ python_min }}
    - whitebox
    - xorg-libx11

test:
  requires:
    - python {{ python_min }}
  imports:
    - whiteboxgui

about:
  home: https://github.com/giswqs/whiteboxgui
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An interactive GUI for WhiteboxTools in a Jupyter-based environment
  doc_url: https://giswqs.github.io/whiteboxgui
  dev_url: https://github.com/giswqs/whiteboxgui

extra:
  recipe-maintainers:
    - giswqs
